# Generated by Django 6.0.4 on 2026-05-26 06:55

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='humanControlled',
        ),
        migrations.RemoveField(
            model_name='team',
            name='purse',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='primaryColor',
            field=models.CharField(default='#f59e0b', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='shortName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbyCode', models.CharField(default=core.models.generate_lobby_code, max_length=8, unique=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purseRemaining', models.IntegerField(default=9000)),
                ('squadSize', models.IntegerField(default=0)),
                ('isAI', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_teams', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'team'), ('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('soldPrice', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('soldTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_entries', to='core.gameteam')),
            ],
        ),
        migrations.CreateModel(
            name='GameAuctionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBid', models.IntegerField(default=0)),
                ('timerEnd', models.DateTimeField(blank=True, null=True)),
                ('round', models.IntegerField(default=0)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_state', to='core.game')),
                ('currentNomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gameplayer')),
                ('highestBidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gameteam')),
            ],
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
